### ISSUE TITLE
Feature request: return to position in feed

### ISSUE THREAD

**Issue by shawnyeager** [eskema/alphaama#2]
First, really enjoying using alphaama. Thanks for making it. 

Would be great to be able to return to my place in my "home" feed when I click to return from a thread. Currently, at least in Chrome for macOS, I'm returned to the top and must scroll to find my place again.

**Comment by eskema** [comment]
hey Shawn, thanks for trying it out. I'm glad you're enjoying it. The behaviour you're describing is what should happen if you click on the colored bars above or below a selected post, it should scroll you to that post in the feed. using the browser back buttons doesn't work at the moment. next version will have this behaviour improved

**Comment by shawnyeager** [comment]
Thanks, @eskema. Interesting. I am clicking above to return, but I get popped to the top of the feed. Maybe I've got a browser extension that's messing things up. I'll see if I can track it down.

**Comment by eskema** [comment]
fixed in v3
