### ISSUE TITLE
NS_ERROR_FAILURE

### ISSUE THREAD

**Issue by theRescuer** [eskema/alphaama#5]
Hi,
Just pasting my public key on the --k prompt I get the following error (which I copied from browser developer console)
Working with Debian + Firefox 02.5.0esr (64 bit)
---
Uncaught 
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, filename: "https://alphaama.com/r/aa--core.js?v=11", lineNumber: 26, columnNumber: 0, data: null, stack: "bbbb@https://alphaama.com/r/aa--core.js?v=11:26:12\nis@https://alphaama.com/r/aa--core.js?v=11:121:19\n" }
​    columnNumber: 0
​    data: null
​    filename: "https://alphaama.com/r/aa--core.js?v=11"
​    lineNumber: 26
    ​message: ""
​    name: "NS_ERROR_FAILURE"
    ​result: 2147500037
​    stack: "bbbb@https://alphaama.com/r/aa--core.js?v=11:26:12\nis@https://alphaama.com/r/aa--core.js?v=11:121:19\n"
​    <prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, … }
​​        columnNumber: 
​​        data: 
​​        filename: 
​​        lineNumber: 
​​​        message: 
​​​        name: 
​​​        result: 
​​​        stack: 
​​​        toString: function toString()
​​​        Symbol(Symbol.toStringTag): "Exception"
​​​        <get columnNumber()>: function columnNumber()
​​​        <get data()>: function data()
​​​        <get filename()>: function filename()
​        <get lineNumber()>: function lineNumber()
​​​        <get message()>: function message()
​​​        <get name()>: function name()
​​​        <get result()>: function result()
​​​        <get stack()>: function stack()
​​​        <set stack()>: function stack()
​​        <prototype>: Object { … }
        
[aa--core.js:26](https://alphaama.com/r/aa--core.js?v=11)
        bbbb https://alphaama.com/r/aa--core.js?v=11:26
        is https://alphaama.com/r/aa--core.js?v=11:121

**Comment by eskema** [comment]
not sure what is causing this, I can't reproduce it on my end.. something with that os / browser combination..
